pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/TechNgine/docker-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t tindog-nginx .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Stop and remove any existing container if running
                    sh 'docker stop tindog-container || true'
                    sh 'docker rm tindog-container || true'

                    // Run the new container
                    sh 'docker run -d --name tindog-container -p 80:80 tindog-nginx'
                }
            }
        }
    }
}
